### PR TITLE
fix panic in Connection::send_packet by returning a Err instead

### PR DESCRIPTION
**Pull request by exoticorn**
`UdpSocket::send_to` will fail with an error if the network interface goes away. (For example, if I disable my wired connection on Linux, if I disable Wlan on my Android phone and probably also when I'm connected to a mobile network and the connection to the cell network is lost.) This should not cause a networking library to panic.

I have changed the return type of `Connection::send_packet` to `Result<u32, Error>` and updated both `Client::send` and `Server::send`. There I _think_ it is still necessary to call `self.ticker.end_tick()` as applicable, which is why I didn't just use the question mark operator to return the error immediately.

I'm also not 100% sure whether aborting the loop over the connections in `Server::send` on the first error is the right thing to do, although it is highly likely that the sends for all other connections will fail as well.

### CODE REVIEW

**Comment by BonsaiDen** [comment]
@exoticorn Thanks for the PR, this is definitely an oversight on my end.

Now, I think that skipping the remaining connections in `Server::send` is fine given the relatively low chances of any further send calls succeeding with the interface being gone.

I'll merge this in once I have figured out what shenanigans broke coveralls.io this time round... :)

**Comment by exoticorn** [comment]
The only possible problem I see with skipping the other connections would be if a send on a connection fails for a reason that does not automatically apply to the other connections. The documentation of `UdpSocket::send_to` reads: "This will return an error when the IP version of the local socket does not match that returned from ToSocketAddrs." So a connection with an incompatible IP version would block other connections from sending. Now, there should be no way for such a connection to end up in the connection vector and I can't think of many other reasons a UDP send could fail only for a specific connection, but who knows... ;)

**Comment by BonsaiDen** [comment]
Thinking about it the other possibility, likely cleaner option, would be to just keep trying until a a certain threshold is exceeded (like XXXms without a "successful" send) and then simply transition the connection to the `Failed` state and handle it like any other connection loss / failure.

**Comment by exoticorn** [comment]
Yeah, that's probably even cleaner. I'm less concerned about the server side, though. If the server loses it's network interface, all is lost anyway (basically). On the client, however, (especially on mobile devices, where the network is a lot more volatile) this needs to handled more gracefully.

**Comment by BonsaiDen** [comment]
I have opened #5 which addresses the issue by implementing the previously described timeout mechanism around `send_to` calls. The timeout is handled via the already existing `Config::connection_drop_threshold` value and the `ConnectionLost` enum variants now contain a boolean value that indicates whether the loss was caused by the remote or locally.

**Comment by exoticorn** [comment]
Your fix looks better than mine, so I'll close this.

**Pull request closed without merging**
